name: realestate-env
channels:
  - defaults
dependencies:
  - python=3.9
  - pandas
  - scikit-learn
  - xgboost
  - lightgbm
  - mlflow
  - flask
  - pip
  - pip:
    - joblib
    - matplotlib
    - requests